@url = http://localhost:3049

### BASE ROUTE
{{url}}

### LOGIN HENDRICK
POST {{url}}/login
content-type: application/json

{
	"username": "hd",
    "password": "hd123"
}

### LOGIN ANDREA
POST {{url}}/login
content-type: application/json
 
{
    "username": "an",
    "password": "an123"
}

### GET CURRENT USER
{{url}}/current-user

### LOGOUT GET
{{url}}/logout