@url = https://l-r-backend.saly-art.de

### BASE ROUTE
{{url}}

### LOGIN HENDRICK
POST {{url}}/login
content-type: application/json

{
	"username": "hd",
    "password": "hd123",
     "safeOriginCode":"4813364"
}

### LOGIN ANDREA
POST {{url}}/login
content-type: application/json
 
{
    "username": "an",
    "password": "an123",
     "safeOriginCode":"4813364"
}

### GET CURRENT USER
{{url}}/current-user

### LOGOUT GET
{{url}}/logout


### REGISTER
POST {{url}}/register
content-type: application/json
 
{
    "username": "an",
    "firstName" : "sa",
    "lastName" : "sa",
    "password": "an123",
    "safeOriginCode":"4813364",
    "email": "sali.taymour@gmail.com"
}
